#!/usr/bin/env node
/**
 * Production runs on PostgreSQL; development and tests use SQLite. Both use the same models in
 * prisma/schema.prisma. This script keeps prisma/postgres/ in step:
 *
 *   node scripts/postgres-schema.mjs <name>   write the PostgreSQL schema and, if the models changed,
 *                                             a new migration prisma/postgres/migrations/<stamp>_<name>
 *   node scripts/postgres-schema.mjs --check  fail if a migration is missing (used in CI)
 *
 * Migrations are produced offline with `prisma migrate diff`, so no PostgreSQL server is needed.
 */
import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const SOURCE = 'prisma/schema.prisma';
const DIR = 'prisma/postgres';
const SNAPSHOT = join(DIR, 'schema.prisma');
const MIGRATIONS = join(DIR, 'migrations');

const arg = process.argv[2];
if (!arg) {
  console.error('Usage: node scripts/postgres-schema.mjs <migration_name> | --check');
  process.exit(2);
}

const source = readFileSync(SOURCE, 'utf8');
if (!/provider\s*=\s*"sqlite"/.test(source)) throw new Error(`${SOURCE} should use the sqlite provider.`);
const header = '// GENERATED by scripts/postgres-schema.mjs from prisma/schema.prisma. Do not edit by hand.\n\n';
const next =
  header +
  // The production image generates its Prisma client from this file (see backend/Dockerfile).
  source.replace(/provider\s*=\s*"sqlite"/, 'provider = "postgresql"');

const previous = existsSync(SNAPSHOT) ? readFileSync(SNAPSHOT, 'utf8') : null;
const tmp = mkdtempSync(join(tmpdir(), 'kp-pg-'));
const nextPath = join(tmp, 'next.prisma');
writeFileSync(nextPath, next);

const diffArgs = previous
  ? ['--from-schema-datamodel', (writeFileSync(join(tmp, 'prev.prisma'), previous), join(tmp, 'prev.prisma'))]
  : ['--from-empty'];
const args = [...diffArgs, '--to-schema-datamodel', nextPath, '--script'].map((a) => (a.startsWith('--') ? a : `"${a}"`));
const sql = execSync(`npx prisma migrate diff ${args.join(' ')}`, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] });
const changed = !/^-- This is an empty migration\.\s*$/m.test(sql) && sql.trim().length > 0;

if (arg === '--check') {
  if (changed || previous !== next) {
    console.error('prisma/postgres is out of date. Run: npm run db:pg -- <migration_name>');
    process.exit(1);
  }
  console.log('PostgreSQL schema and migrations are up to date.');
  process.exit(0);
}

if (!/^[a-z0-9_]+$/.test(arg)) throw new Error('Migration names use lower-case letters, digits and underscores.');
mkdirSync(MIGRATIONS, { recursive: true });
writeFileSync(join(MIGRATIONS, 'migration_lock.toml'), '# Please do not edit this file manually\nprovider = "postgresql"\n');
if (changed) {
  const stamp = new Date().toISOString().replace(/\D/g, '').slice(0, 14);
  const dir = join(MIGRATIONS, `${stamp}_${arg}`);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'migration.sql'), sql);
  console.log(`Wrote ${dir}/migration.sql`);
} else {
  console.log('No model changes; no new migration needed.');
}
writeFileSync(SNAPSHOT, next);
